services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/log/:/mosquitto/log/
      - data:/mosquitto:data/
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  data: ~